version: "3"

services:
  bot:
    build:
      context: .
    restart: always
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`bot.donchenko.in.ua`)"
      - "traefik.http.routers.bot.entrypoints=web"

networks:
  traefik-proxy:
    external: true
