name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: donchenko/tgdefbot:latest
          build-args: |
            TOKEN=${{ secrets.TOKEN }}
            MERRIAM_WEBSTER_API_KEY=${{ secrets.MERRIAM_WEBSTER_API_KEY }}
      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: 59666312
          token: ${{ secrets.TOKEN }}
          message: "Build completed successfully"
