name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tgdefbot:latest

    - name: Run and check the container
      run: |
        docker run -d -e TOKEN=${{ secrets.TOKEN }} -e MERRIAM_WEBSTER_API_KEY=${{ secrets.MERRIAM_WEBSTER_API_KEY }} --name test_container ${{ secrets.DOCKER_HUB_USERNAME }}/tgdefbot:latest python test_bot.py
        sleep 10
        if docker logs test_container | grep "Test passed"; then
          echo "Tests passed, container is working correctly"
        else
          echo "Tests failed, container is not working correctly" && exit 1
        fi
        docker rm test_container
    
    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tgdefbot:latest

    - name: Notify Telegram
      uses: appleboy/telegram-action@master
      with:
        to: 59666312
        token: ${{ secrets.TOKEN }}
        message: "Build completed successfully"
