name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest

    - name: Run and check the container
      run: |
        docker run --rm -d --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest
        sleep 10
        if docker logs test_container | grep "Starting the bot"; then
          echo "Container started successfully"
        else
          echo "Container failed to start" && exit 1
        fi

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest
